# Generated by Django 4.2.5 on 2025-08-11 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_clinical_note_id_remove_patient_lab_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Risk_level', models.CharField(max_length=50)),
                ('Score', models.FloatField()),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
