# Generated by Django 4.2.5 on 2025-08-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Risk_score',
        ),
    ]
