# Generated by Django 4.2.5 on 2025-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cust_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CustFirstName', models.CharField(max_length=50)),
                ('CustLastName', models.CharField(max_length=50)),
                ('CustMiddleInit', models.CharField(max_length=1)),
                ('CustSuffix', models.CharField(max_length=10)),
                ('CustDOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('CustomerType', models.CharField(max_length=50)),
            ],
        ),
    ]
