# Generated by Django 4.2.5 on 2025-08-10 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Cust_ID',
            new_name='Cust_id',
        ),
        migrations.CreateModel(
            name='Patient_lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('BMI', models.FloatField()),
                ('Systolic_BP', models.FloatField()),
                ('Diastolic_BP', models.FloatField()),
                ('Total_Cholesterol', models.FloatField()),
                ('HDL_Cholesterol', models.FloatField()),
                ('LDL_Cholesterol', models.FloatField()),
                ('Triglycerides', models.FloatField()),
                ('Smoking_status', models.BooleanField()),
                ('Physical_activity', models.CharField(max_length=50)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Clinical_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Medical_specialty', models.CharField(max_length=100)),
                ('Sample_name', models.CharField(max_length=100)),
                ('Transcription', models.TextField()),
                ('Keywords', models.TextField()),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
