# Generated by Django 4.2.5 on 2025-08-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cust_id_customer_cust_id_patient_lab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinical_note',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient_lab',
            name='id',
        ),
        migrations.AddField(
            model_name='clinical_note',
            name='Note_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_lab',
            name='Lab_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
