# Generated by Django 4.2.5 on 2025-08-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_clinical_note_id_remove_patient_lab_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinical_note',
            name='Note_id',
        ),
        migrations.RemoveField(
            model_name='patient_lab',
            name='Lab_id',
        ),
        migrations.AddField(
            model_name='clinical_note',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_lab',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
