# Generated by Django 4.2.5 on 2025-08-12 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nlp_model_registry_modelregistry_risk_score_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='risk_featuresnapshot',
            name='core_risk_f_Patient_02b089_idx',
        ),
        migrations.RemoveIndex(
            model_name='risk_score',
            name='core_risk_s_Patient_18014f_idx',
        ),
        migrations.AddField(
            model_name='note_prediction',
            name='Predicted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 17, 21, 43, 674505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='risk_featuresnapshot',
            name='Observed_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 17, 21, 43, 673505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='risk_score',
            name='Score_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 17, 21, 43, 673505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='note_prediction',
            index=models.Index(fields=['Note_id', '-Predicted_at'], name='core_note_p_Note_id_499db1_idx'),
        ),
        migrations.AddIndex(
            model_name='risk_featuresnapshot',
            index=models.Index(fields=['Patient_id', '-Observed_at'], name='core_risk_f_Patient_309eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='risk_score',
            index=models.Index(fields=['Patient_id', '-Score_date'], name='core_risk_s_Patient_2dfc24_idx'),
        ),
    ]
