# Generated by Django 4.2.5 on 2025-08-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_note_prediction_predicted_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelRegistry',
        ),
        migrations.DeleteModel(
            name='NLP_model_registry',
        ),
    ]
