# Generated by Django 4.2.5 on 2025-08-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_modelregistry_delete_nlp_model_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.BooleanField()),
                ('Index_date', models.DateField(blank=True, null=True)),
                ('Horizon_days', models.IntegerField(default=180)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='risk_score',
            name='core_risk_s_Patient_2dfc24_idx',
        ),
        migrations.AddIndex(
            model_name='risk_score',
            index=models.Index(fields=['Patient_id', '-Score'], name='core_risk_s_Patient_e6ab88_idx'),
        ),
        migrations.AddField(
            model_name='diabetesoutcome',
            name='Patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AddIndex(
            model_name='diabetesoutcome',
            index=models.Index(fields=['Patient_id', '-Created_at'], name='core_diabet_Patient_7c4533_idx'),
        ),
        migrations.AddIndex(
            model_name='diabetesoutcome',
            index=models.Index(fields=['Index_date'], name='core_diabet_Index_d_819d82_idx'),
        ),
        migrations.AddConstraint(
            model_name='diabetesoutcome',
            constraint=models.UniqueConstraint(fields=('Patient_id', 'Index_date', 'Horizon_days'), name='uniq_patient_date_horizon'),
        ),
    ]
