# Generated by Django 4.2.5 on 2025-08-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_diabetesoutcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk_score',
            name='Band',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
