# Generated by Django 4.2.5 on 2025-08-13 00:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_note_prediction_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.FloatField()),
                ('HighRisk', models.BooleanField(default=False)),
                ('Scored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Risk_Score',
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['Patient_id', '-Scored_at'], name='core_risksc_Patient_793ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['HighRisk', '-Scored_at'], name='core_risksc_HighRis_0c7161_idx'),
        ),
    ]
