# Generated by Django 4.2.5 on 2025-08-13 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_riskscore_delete_risk_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Predicted_specialty', models.CharField(max_length=50)),
                ('Confidence', models.FloatField()),
                ('Predicted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinical_note')),
            ],
            options={
                'indexes': [models.Index(fields=['Note', '-Predicted_at'], name='core_notepr_Note_id_33edcc_idx'), models.Index(fields=['Predicted_specialty', '-Predicted_at'], name='core_notepr_Predict_e37b2b_idx')],
            },
        ),
    ]
